#!/bin/bash
# Job 084: the all-in-VRAM column of Table 1 and routing traces of the measured workload, on an RTX PRO 6000 Blackwell
# Workstation (96 GB; the same memory bandwidth as the RTX 5090, 1.79 TB/s, with room for every weight).
#  A. All in VRAM: stock llama.cpp with every weight on the GPU, Table 1 protocol (30 AIME-25 problems, 256 tokens,
#     greedy, held-out warm-up, session, GPU-side sampling), launches 1 and 2, for Qwen3-30B-A3B BF16 and gpt-oss-120b
#     (the latter repeats job 075's cell on the same card model). Plus ours with 128 slots per layer (every expert on
#     the GPU, launch 1): what the cache costs when the model fits.
#  B. Routing traces: for both models, the 30 AIME-25 prompts exactly as llama-server templates and tokenizes them
#     (its /apply-template and /tokenize), 256 greedy tokens generated by llama-ec-bench on the GPU (--gen-temp 1e-4),
#     then teacher-forced over that text with --lookahead (router choices per decode step and layer). These feed the
#     speed-limit column (scripts/speed_limit.py with the headline machine's bandwidth probe) and the foresight study.
# Predictions, committed before launch:
#   1. Qwen3-30B-A3B BF16 all in VRAM runs at 120-190 tok/s;
#   2. gpt-oss-120b all in VRAM is within 5% of job 075's 261.4 tok/s;
#   3. ours with every expert in its slots is within 5% of stock all-in-VRAM on both models;
#   4. (scored offline) on these traces, the simulated deployed policy's hit rate is within 5 points of the engine's
#      measured hit rate at every Table 1 budget (jobs 080/081), and ours runs at 20-50% of the speed limit at every
#      Table 1 budget.
set -x
exec 2>&1
export CUDA_VISIBLE_DEVICES=0
. "$(cd "$(dirname "$0")" && pwd)/ec2/setup.sh"
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3-venv python3-pip >> $OUT/apt.txt 2>&1
CORES=$(usable_cores); echo "usable physical cores $CORES (nproc $(nproc))" | tee $OUT/cores.txt
R() { local t=$1; shift; timeout "$t" "$@"; }
FT=$WORK/ft; export FT_DIR=$FT   # FreeToken's benchmark module supplies the AIME prompt format (not installed or run)
( cd $WORK && git init -q ft && cd ft && git remote add origin https://github.com/FlashML-org/FreeToken &&
  git fetch -q --depth 1 origin 0d652e73a452d014ac5441a15baa75348e9fcb0a && git checkout -q FETCH_HEAD ) || echo "FreeToken clone FAILED"
python3 -m pip install -q --break-system-packages uv huggingface_hub hf_xet > $OUT/pip_uv.txt 2>&1
VE=$WORK/venv
( uv venv -q $VE && . $VE/bin/activate && uv pip install -q torch --index-url https://download.pytorch.org/whl/cpu &&
  uv pip install -q numpy transformers sentencepiece safetensors protobuf huggingface_hub hf_xet ) > $OUT/venv_install.txt 2>&1
echo "venv install rc=$?"
PY=$VE/bin/python
$PY -c "import torch, transformers, huggingface_hub; print(torch.__version__, transformers.__version__)" | tee $OUT/venv_ok.txt
mkdir -p $M
HFD=$M/gpt-oss-120b
( t0=$(date +%s)
  $PY -c "import sys; from huggingface_hub import snapshot_download as s; s('openai/gpt-oss-120b', local_dir=sys.argv[1], allow_patterns=['*.json', '*.jinja', '*.txt'])" "$HFD"
  $PY -c "import sys; from huggingface_hub import hf_hub_download as d; d('ggml-org/gpt-oss-120b-GGUF', 'gpt-oss-120b-MXFP4.gguf', local_dir=sys.argv[1])" "$M"
  echo "gguf hf download rc=$? in $(( $(date +%s) - t0 )) s"; ls -la $M/gpt-oss-120b-MXFP4.gguf
  if [ ! -s $M/gpt-oss-120b-MXFP4.gguf ]; then
    rm -f $M/gpt-oss-120b-MXFP4.gguf
    for i in 1 2 3; do getmodel ggml-org/gpt-oss-120b-GGUF gpt-oss-120b-MXFP4.gguf; [ -f $M/gpt-oss-120b-MXFP4.gguf ] && break; done
  fi
) > $OUT/dl_gguf.txt 2>&1 &
DLG=$!
HFQ=$M/Qwen3-30B-A3B
( t0=$(date +%s); $PY -c "import sys; from huggingface_hub import snapshot_download as s; s('Qwen/Qwen3-30B-A3B', local_dir=sys.argv[1])" "$HFQ"
  echo "qwen3 hf download rc=$? in $(( $(date +%s) - t0 )) s"; du -sh "$HFQ" ) > $OUT/dl_qwen3.txt 2>&1 &
DLQ=$!
$PY -c "from huggingface_hub import hf_hub_download as d; import shutil; shutil.copy(d('math-ai/aime25','test.jsonl',repo_type='dataset'), '$WORK/aime25.jsonl')" && export FREETOKEN_AIME25_JSONL=$WORK/aime25.jsonl
wc -l $WORK/aime25.jsonl | tee $OUT/aime25_count.txt
$PY - "$WORK/warmup.txt" <<'PY' > $OUT/warmup_source.txt 2>&1
import json, sys
sys.path.insert(0, "/work/ft/benchmarks")
import bench_decode_moe as B
text = None
for repo, fn in (("math-ai/aime24", "test.jsonl"), ("HuggingFaceH4/aime_2024", "train.jsonl")):
    try:
        from huggingface_hub import hf_hub_download
        text, _ = B.load_problem(hf_hub_download(repo, fn, repo_type="dataset"), 0)
        print("warm-up prompt:", repo, fn, "problem 0")
        break
    except Exception as e:
        print("no", repo, fn, repr(e)[:200])
if text is None:
    text = ("Let S be the set of positive integers n at most 2024 such that n^2 + n + 41 is divisible by 43. "
            "Find the number of elements of S.\n" + B.BOXED_INSTRUCTION)
    print("warm-up prompt: fixed fallback text")
open(sys.argv[1], "w").write(text)
PY
cat $OUT/warmup_source.txt
build_tree $WORK/lc-ec "$J/llama.cpp-expert-cache-4da6337.patch" llama-ec-bench llama-server
build_tree $WORK/lc-stock "" llama-server
EC_SERVER=$WORK/lc-ec/build/bin/llama-server
wait $DLG $DLQ
cat $OUT/dl_gguf.txt $OUT/dl_qwen3.txt
F=$M/gpt-oss-120b-MXFP4.gguf
[ -s "$F" ] && echo "GGUF ok $(stat -c %s $F) bytes" || echo "GGUF MISSING"
GQ=$M/Qwen3-30B-A3B-BF16.gguf
( t0=$(date +%s); PYTHONPATH=$WORK/lc-stock/gguf-py $PY $WORK/lc-stock/convert_hf_to_gguf.py "$HFQ" --outtype bf16 --outfile $GQ
  echo "convert rc=$? in $(( $(date +%s) - t0 )) s"; ls -la $GQ ) > $OUT/convert_qwen3.txt 2>&1
tail -2 $OUT/convert_qwen3.txt
platform
H=$(( CORES > 4 ? CORES - 2 : 2 ))
LXB='{"min_p": 0.0, "seed": 1234, "backend_sampling": true}'
OT="-ot '\\.ffn_(up|down|gate|gate_up)_exps=CUDA_Host'"
ECENV="env LLAMA_EC_POLICY=dfa LLAMA_EC_KAPPA=1 LLAMA_EC_MAILBOX=1 LLAMA_EC_TDEC=1 LLAMA_EC_HELPERS=$H"
waitfree() {
  for i in $(seq 120); do u=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits | head -1); [ "${u:-0}" -lt 1500 ] && return; sleep 2; done
  echo "GPU memory still in use: $u MiB"
}
cl() {  # model-dir label launch meta [client args...]
  local hf=$1 lab=$2 L=$3 meta=$4; shift 4
  waitfree
  R 60m $PY $J/bs1_client.py --model $hf --problems $(seq -s, 0 29) --decode 256 --greedy --warmup once --warmup-prompt $WORK/warmup.txt \
    --launch $L --label $lab --meta "$meta" --json $OUT/bs1.jsonl --log $OUT/srv_${lab}_L$L.log "$@"
  echo "$lab launch $L rc=$?"
}
corpus() {  # gguf server-flags out.jsonl: the 30 AIME-25 prompts as llama-server templates and tokenizes them
  local g=$1 flags=$2 out=$3 port=8199
  waitfree
  eval "$STOCK_SERVER -m $g -ngl 0 --no-warmup -c 4096 -np 1 --no-webui $flags --port $port" > $out.srv.log 2>&1 &
  local pid=$!
  for i in $(seq 180); do curl -sf localhost:$port/health > /dev/null && break; sleep 2; done
  $PY - "$port" "$out" <<'PY'
import json, sys, urllib.request
sys.path.insert(0, "/work/ft/benchmarks")
import bench_decode_moe as B
import os
port, out = sys.argv[1], sys.argv[2]
def post(path, body):
    req = urllib.request.Request(f"http://localhost:{port}{path}", data=json.dumps(body).encode(), headers={"Content-Type": "application/json"})
    return json.load(urllib.request.urlopen(req, timeout=120))
with open(out, "w") as f:
    for p in range(30):
        text, _ = B.load_problem(os.environ["FREETOKEN_AIME25_JSONL"], p)
        prompt = post("/apply-template", {"messages": [{"role": "user", "content": text}],
                                          "chat_template_kwargs": {"enable_thinking": True}})["prompt"]
        ids = post("/tokenize", {"content": prompt, "add_special": True, "parse_special": True})["tokens"]
        f.write(json.dumps({"domain": "aime25", "problem": p, "prompt_len": len(ids), "ids": ids + [ids[-1]]}) + "\n")
        if p == 0:
            print("problem 0 prompt:", repr(prompt[:400]), "...", len(ids), "tokens")
print("corpus rows:", sum(1 for _ in open(out)))
PY
  kill $pid; wait $pid 2>/dev/null
}
traces() {  # tag gguf server-flags: generate 256 greedy tokens per prompt, then record routing teacher-forced
  local tag=$1 g=$2 flags=$3
  corpus $g "$flags" $OUT/aime25_prompts_$tag.jsonl > $OUT/corpus_$tag.txt 2>&1; cat $OUT/corpus_$tag.txt
  waitfree
  R 40m $EC_BIN -m $g --corpus $OUT/aime25_prompts_$tag.jsonl -t $CORES --n-prefill 1024 --n-decode 256 \
    --gen-temp 0.0001 --gen-seed 0 --gen-out $OUT/aime25_owntext_$tag.jsonl > /dev/null 2> $OUT/gen_$tag.err
  echo "$tag generation rc=$? rows $(wc -l < $OUT/aime25_owntext_$tag.jsonl)"
  R 60m $EC_BIN -m $g --corpus $OUT/aime25_owntext_$tag.jsonl -t $CORES --n-prefill 1024 --n-decode 256 \
    --lookahead $OUT/la_aime25_$tag.bin > $OUT/la_aime25_$tag.jsonl 2> $OUT/la_$tag.err
  echo "$tag lookahead rc=$? $(ls -la $OUT/la_aime25_$tag.bin)"
  tail -3 $OUT/la_$tag.err
}
# ---- gpt-oss-120b
LSG="-m $F -ngl 99 -fa on -lm none -t $CORES -np 1 -c 8448 --no-webui"
for L in 1 2; do cl $HFD g_vram $L '{"model": "gpt-oss-120b", "system": "llama.cpp, all in VRAM"}' --extra "$LXB" --cmd "$STOCK_SERVER $LSG --port {port}"; done
cl $HFD g_ours_C128 1 '{"model": "gpt-oss-120b", "system": "ours v2", "C": 128}' --extra "$LXB" \
  --cmd "$ECENV LLAMA_EC_SLOTS=128 LLAMA_EC_FETCH=0,0,1,1,2 LLAMA_EC_STATS=$OUT/srv_g_ours_C128.json $EC_SERVER $LSG $OT --port {port}"
traces gptoss $F ""
# ---- Qwen3-30B-A3B BF16
if [ -s "$GQ" ]; then
  LSQ="-m $GQ -ngl 99 -fa on -lm none -t $CORES -np 1 -c 2048 --no-webui --jinja"
  for L in 1 2; do cl $HFQ q_vram $L '{"model": "Qwen3-30B-A3B", "system": "llama.cpp, all in VRAM"}' --extra "$LXB" --cmd "$STOCK_SERVER $LSQ --port {port}"; done
  cl $HFQ q_ours_C128 1 '{"model": "Qwen3-30B-A3B", "system": "ours v2", "C": 128}' --extra "$LXB" \
    --cmd "$ECENV LLAMA_EC_SLOTS=128 LLAMA_EC_FETCH=0,0,1,1,2,3,3,4,5 LLAMA_EC_STATS=$OUT/srv_q_ours_C128.json $EC_SERVER $LSQ $OT --port {port}"
  traces qwen3 $GQ "--jinja"
else
  echo "Qwen3 GGUF missing: Qwen3 part skipped"
fi
cd $WORK
for f in $OUT/srv_*.log; do tail -n 60 "$f" > "$f.tail"; done; find $OUT -name 'srv_*.log' -delete
$PY - "$OUT" <<'PY' | tee $OUT/summary.txt
import json, sys, os, statistics as st
out = sys.argv[1]
rows = [json.loads(l) for l in open(f"{out}/bs1.jsonl")] if os.path.exists(f"{out}/bs1.jsonl") else []
by = {}
for r in rows: by.setdefault((r["label"], r["launch"]), []).append(r)
for (lab, L), v in sorted(by.items()):
    print(f"{lab:16s} launch {L}: {st.mean(r['decode_tok_s'] for r in v):7.2f} tok/s (n={len(v)}), VRAM {v[0].get('vram_used_gib')}")
for tag in ("gptoss", "qwen3"):
    p = f"{out}/la_aime25_{tag}.jsonl"
    if os.path.exists(p):
        v = [json.loads(l) for l in open(p) if l.startswith("{")]
        v = [r for r in v if "nll_sum" in r]
        if v:
            print(f"{tag}: teacher-forced own text, {len(v)} sequences, NLL {sum(r['nll_sum'] for r in v) / sum(r['nll_n'] for r in v):.3f} nats/token")
PY
