"""The audit's rows as an appendix table (paper/tab_audit.tex) from prereg/audit/audit_sol.json: every published
measurement with its system, model, GPU, per-layer capacity, experts and top-k, the measured speed, the bound at
datasheet-physical ceilings, how the optimum's reads were obtained (an on-policy trace of the model, uniform routing,
no GPU expert capacity, or every expert resident) and the percentage.

    python scripts/audit_table.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
CITE = {"Fiddler": "kamahori2024fiddler", "ProMoE": "song2024promoe", "KTrans.": "ktransformers", "HybriMoE": "zhong2025hybrimoe",
        "Fate": "fate2025", "SP-MoE": "spmoe", "MoE-SpeQ": "moespeq", "CG-collab": "huang2025cpugpu", "FreeToken": "freetoken",
        "SeqMoE": "wang2026seqmoe", "NV pipe": "pipelinedsharding2026", "lcpp forks": "leloch2026", "lcpp PR": "llamacpppr27861"}
NAME = {"KTrans.": "KTransformers", "CG-collab": "CPU--GPU collab.", "NV pipe": "Pipelined sharding", "lcpp forks": "llama.cpp fork (leloch)", "lcpp PR": "llama.cpp PR 27861"}
CLS = {"trace": "trace", "iid": "uniform", "nocap": "no slots", "allfit": "all fit"}


def tex(s):
    return s.replace("&", "\\&").replace("%", "\\%").replace("_", "\\_").replace("#", "\\#")


def main():
    a = json.load(open(os.path.join(ROOT, "prereg", "audit", "audit_sol.json")))
    lines = []
    last = None
    for r in a["rows"]:
        sysname = NAME.get(r["label"], r["label"])
        cite = CITE.get(r["label"])
        first = sysname + (f"~\\cite{{{cite}}}" if cite else "") if r["label"] != last else ""
        last = r["label"]
        model = r["model"].split(" (")[0]
        gpu = r["gpu"].replace(" (PCIe)", "")
        lines.append(f"{first} & {tex(model)} & {tex(gpu)} & {r['C_per_layer']} & {r['E']}/{r['k']} & {r['system_tok_s']:.1f} & {r['sol_tok_s']:.0f} & {CLS[r['cls']]} & {r['pct_of_sol']:.1f} \\\\")
    cs = a["class_stats"]
    with open(os.path.join(ROOT, "paper", "tab_audit.tex"), "w") as f:
        f.write("% generated by scripts/audit_table.py from prereg/audit/audit_sol.json\n")
        f.write("\\begin{footnotesize}\n\\setlength\\tabcolsep{3pt}\n")
        f.write("\\begin{longtable}{@{}llllrrrlr@{}}\n")
        f.write("\\caption{The audit's rows (\\cref{sec:audit}): every published batch-1 measurement we scored, with the system's stated "
                "hardware, its experts per layer resident on the GPU ($C$), the model's experts and top-$k$, the published speed, the "
                "bound at datasheet-physical ceilings (GPU datasheet bandwidth, the top of the host-DRAM band, datasheet PCIe, no latencies; "
                "\\texttt{scripts/audit.py}), how the optimum's reads were obtained (\\emph{trace}: Belady's MIN with bypass on an on-policy "
                "routing trace of the model; \\emph{uniform}: independent uniform routing, which overstates the reads and so the percentage; "
                "\\emph{no slots}: no GPU expert capacity, the CPU-only rate is the bound; \\emph{all fit}: every expert resident, nothing "
                "offloaded) and the percentage of the bound. Medians: trace %.1f\\%% ($n{=}%d$), uniform %.1f\\%% (%d), no slots %.1f\\%% (%d), "
                "all fit %.1f\\%% (%d), all rows %.1f\\%% (%d). Rows below 5\\%% are more likely configuration mismatches with the "
                "bound's assumptions (precision, dense layers on the CPU, end-to-end timing) than inefficiency, and are not adjudicated.}"
                "\\label{tab:audit}\\\\\n" % (cs["trace"]["median"], cs["trace"]["n"], cs["iid"]["median"], cs["iid"]["n"], cs["nocap"]["median"], cs["nocap"]["n"],
                                              cs["allfit"]["median"], cs["allfit"]["n"], cs["all"]["median"], cs["all"]["n"]))
        f.write("\\toprule\nSystem & Model & GPU & $C$ & $E/k$ & tok/s & bound & reads & \\% \\\\\\midrule\n\\endfirsthead\n")
        f.write("\\toprule\nSystem & Model & GPU & $C$ & $E/k$ & tok/s & bound & reads & \\% \\\\\\midrule\n\\endhead\n")
        f.write("\\midrule\\multicolumn{9}{r}{\\emph{continued}}\\\\\n\\endfoot\n\\bottomrule\n\\endlastfoot\n")
        f.write("\n".join(lines) + "\n")
        f.write("\\end{longtable}\n\\end{footnotesize}\n")
    print(f"wrote paper/tab_audit.tex with {len(lines)} rows")


if __name__ == "__main__":
    main()
