"""Our cache scored by the audit's own procedure, for a like-for-like comparison with the published rows: the bound of
mosl.perfmodel.speed_of_light_time at datasheet ceilings (RTX 5090 1,792 GB/s, PCIe 5.0 x16 63 GB/s, the top of the
host's DDR5 dual-channel band, every efficiency 1, no latencies), MIN-with-bypass misses at C slots per layer from the
same on-policy traces the audit uses (scripts/audit.py: mstar), against the measured speeds of Table 1 (hosts B and S;
prereg/audit/audit_sol.json reference points for host B, prereg/headline_s_*.json for host S via the paper's macros).
Writes prereg/audit/audit_ours.json and paper/wsg_auditours.tex.

    python scripts/audit_ours.py
"""
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from mosl.archs import shape  # noqa: E402
from mosl.perfmodel import HW, Workload, speed_of_light_time  # noqa: E402
from scripts.audit import PHYS, mstar  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
RES = "/home/claude/gpu-branch/results"
# Table 1 (tab_headline.tex), ours, tok/s
OURS = {"B": {("openai/gpt-oss-120b", 14): 69.9, ("openai/gpt-oss-120b", 32): 109.2, ("openai/gpt-oss-120b", 51): 152.5,
              ("Qwen/Qwen3-30B-A3B", 16): 40.0, ("Qwen/Qwen3-30B-A3B", 32): 63.1, ("Qwen/Qwen3-30B-A3B", 56): 108.2},
        "S": {("openai/gpt-oss-120b", 14): 57.9, ("openai/gpt-oss-120b", 32): 94.1, ("openai/gpt-oss-120b", 51): 133.6,
              ("Qwen/Qwen3-30B-A3B", 16): 33.5, ("Qwen/Qwen3-30B-A3B", 32): 53.9, ("Qwen/Qwen3-30B-A3B", 56): 95.8}}
BITS = {"openai/gpt-oss-120b": (4.25, 16), "Qwen/Qwen3-30B-A3B": (16, 16)}
DDR5_TOP = 96.0   # dual-channel DDR5-6000, the top of a desktop AM5 band (both hosts are AM5, Ryzen 9 9950X3D / 9950X)


def main():
    rng = np.random.default_rng(0)
    out = []
    for host, rows in OURS.items():
        for (repo, C), tok in rows.items():
            s = shape(repo)
            b_exp, b_dense = BITS[repo]
            w = Workload(s, b_exp, b_dense, ctx=512)
            m, src = mstar(repo, s.n_experts, w.k, C, RES, rng)
            t = speed_of_light_time(w, HW(1792, DDR5_TOP, 63.0), PHYS, m)
            out.append(dict(host=host, repo=repo, C=C, ours_tok_s=tok, sol_tok_s=1 / t, pct=100 * tok * t, mstar=m, mstar_source=src))
            print(f"host {host} {repo:22s} C={C:3d} bound {1 / t:6.1f} tok/s  ours {tok:6.1f}  {100 * tok * t:4.1f}%")
    json.dump(out, open(P("prereg", "audit", "audit_ours.json"), "w"), indent=1)
    pc = [r["pct"] for r in out]
    with open(P("paper", "wsg_auditours.tex"), "w") as f:
        f.write("% generated by scripts/audit_ours.py\n")
        f.write(f"\\newcommand{{\\audOursMin}}{{{min(pc):.0f}}}\n\\newcommand{{\\audOursMax}}{{{max(pc):.0f}}}\n")
        f.write(f"\\newcommand{{\\audOursMed}}{{{float(np.median(pc)):.0f}}}\n")


if __name__ == "__main__":
    main()
