"""The horizon rule on the routing the engine runs: D(W50)/C, the distinct experts a layer requests within the window
that closes half of MIN's read gap over admitting every miss, on the AIME-25 traces of the engine experiments (W50 from
prereg/value_map.json as in scripts/value_paper.py; D(W) as in scripts/w50_rebaseline.py). Writes paper/wsg_dcaime.tex.

    python scripts/dc_aime.py
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from w50_rebaseline import _distinct  # noqa: E402
from value_paper import w_at, CELLS  # noqa: E402
from speed_limit_v2 import TRACES  # noqa: E402

P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
MODEL = {"gpt-oss-120b": "gpt-oss-120b", "qwen3-30b-a3b": "qwen3-30b-a3b-bf16"}


def main():
    vm = json.load(open(P("prereg", "value_map.json")))
    D = {}
    for m, path in TRACES.items():
        z = np.load(path)
        act = z["act"].astype(np.int64)          # [T, L, k]
        E = int(z["n_expert"])
        d = np.zeros(65)
        for l in range(act.shape[1]):
            d += _distinct(np.ascontiguousarray(act[:, l, :]), E, 64)
        D[m] = d / act.shape[1]
    M, out = {}, {}
    for key, lab, nm in CELLS:
        model, C = key.rsplit(" C", 1)
        C = int(C)
        d = D[MODEL[model]]
        k = int(round(d[1]))
        w = w_at(vm[key]["share"])
        dw = k * w if w < 1 else float(np.exp(np.interp(np.log(w), np.log(np.arange(1, 65)), np.log(d[1:65]))))
        out[lab] = dict(W50=w, D=dw, C=C, D_over_C=dw / C)
        M[f"dcAime{nm}"] = f"{dw / C:.2f}"
    v = [o["D_over_C"] for o in out.values()]
    M["dcAimeMin"] = f"{min(v):.2f}"; M["dcAimeMax"] = f"{max(v):.2f}"
    json.dump(out, open(P("prereg", "dc_aime.json"), "w"), indent=1)
    with open(P("paper", "wsg_dcaime.tex"), "w") as f:
        f.write("% generated by scripts/dc_aime.py\n")
        for k in sorted(M):
            f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    print(json.dumps(out, indent=1)); print(M)


if __name__ == "__main__":
    main()
