"""The IEEE build's bibliographies: refs.bib and refs_wsg.bib with venue names in IEEE's abbreviated form ("Proc.",
"Int. Conf.", "Commun. ACM"), in the booktitle and journal fields only. Writes paper/refs_ieee.bib and
paper/refs_wsg_ieee.bib; build_ieee.sh runs it before LaTeX.

    python scripts/ieee_bib.py
"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
# IEEE's abbreviations of words in venue names (IEEE Reference Guide), longest first where one contains another
WORDS = [
    ("Proceedings of the ACM on", "Proc. ACM"), ("Proceedings of the", "Proc."), ("Proceedings of", "Proc."),
    ("Advances in Neural Information Processing Systems", "Adv. Neural Inf. Process. Syst."),
    ("Communications of the ACM", "Commun. ACM"), ("Journal of the ACM", "J. ACM"),
    ("SIAM Journal on Computing", "SIAM J. Comput."), ("Journal of Heuristics", "J. Heuristics"),
    ("Discrete Applied Mathematics", "Discrete Appl. Math."),
    ("International", "Int."), ("Conference", "Conf."), ("Symposium", "Symp."), ("Annual", "Annu."),
    ("Transactions", "Trans."), ("Machine Learning", "Mach. Learn."), ("Systems", "Syst."),
    ("Computer-Aided", "Comput.-Aided"), ("Computer Architecture", "Comput. Archit."),
    ("Architectural", "Archit."), ("Programming", "Program."), ("Languages", "Lang."), ("Operating", "Oper."),
    ("Principles", "Princ."), ("Design", "Des."), ("Automation", "Autom."), ("Networked", "Netw."),
    ("Implementation", "Implement."), ("Measurement", "Meas."), ("Analysis", "Anal."), ("Computing", "Comput."),
    ("Management", "Manage."), ("Representations", "Represent."), ("Association", "Assoc."),
    ("Computational", "Comput."), ("Modeling", "Model."), ("Optimization", "Optim."), ("Networks", "Netw."),
    ("Europe", "Eur."), ("Learning", "Learn."),
]
FIELD = re.compile(r"(\b(?:booktitle|journal)\s*=\s*)(\{(?:[^{}]|\{[^{}]*\})*\})", re.I)


def abbreviate(v):
    for a, b in WORDS:
        v = v.replace(a, b)
    return v.replace("Conf. on ", "Conf. ").replace("Symp. on ", "Symp. ")


def main():
    for src, dst in (("refs.bib", "refs_ieee.bib"), ("refs_wsg.bib", "refs_wsg_ieee.bib")):
        s = open(os.path.join(ROOT, "paper", src)).read()
        s = FIELD.sub(lambda m: m.group(1) + abbreviate(m.group(2)), s)
        s = s.replace("Accepted at DAC 2026 (per arXiv v2)", "Accepted at DAC 2026")
        open(os.path.join(ROOT, "paper", dst), "w").write(f"% generated by scripts/ieee_bib.py from {src}\n" + s)


if __name__ == "__main__":
    main()
