"""Macros and table for the learned admission order replayed offline (prereg/learned_offline.json, written by
scripts/learned_policy6.py: trained on each model's mixed-domain trace, replayed on the AIME-25 routing the engine runs).

Writes paper/wsg_learned.tex (macros) and paper/tab_learned.tex. The engine's variant is the 8-bit cross-layer one
("q8"); the float and same-layer-only ("nocross") variants are reported beside it.

    python scripts/learned_paper.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731

CELLS = [("gpt-oss-120b", 14, "GLow", "gpt-oss 11\\%", True), ("gpt-oss-120b", 32, "GMid", "gpt-oss 25\\%", True),
         ("gpt-oss-120b", 51, "GHigh", "gpt-oss 40\\%", False), ("qwen3-30b-a3b", 16, "QLow", "Qwen3 12.5\\%", True),
         ("qwen3-30b-a3b", 32, "QMid", "Qwen3 25\\%", True), ("qwen3-30b-a3b", 56, "QHigh", "Qwen3 43.75\\%", False)]


def main():
    d = json.load(open(P("prereg", "learned_offline.json")))
    M = {}

    def put(name, val):
        assert not any(ch.isdigit() for ch in name), name
        M[name] = val

    def rng(prefix, vals, fmt="{:.0f}"):
        put(prefix + "Min", fmt.format(min(vals))); put(prefix + "Max", fmt.format(max(vals)))

    q = {(m, C): d[f"{m} C{C} q8"] for m, C, *_ in CELLS}
    nc = {(m, C): d[f"{m} C{C} nocross"] for m, C, *_ in CELLS}
    hb = [(m, C) for m, C, _, _, h in CELLS if h]
    rng("lrnFetchHost", [100 * q[c]["closed_fetch_to_opt"] for c in hb])
    rng("lrnDepHost", [100 * q[c]["closed_deployed_to_opt"] for c in hb])
    rng("lrnSingleHost", [100 * q[c]["closed_deployed_to_opt_single_read"] for c in hb])
    rng("lrnFewerFetchHost", [100 * (1 - q[c]["learned"] / q[c]["dfa-fetch"]) for c in hb])
    rng("lrnFewerDepHost", [100 * (1 - q[c]["learned"] / q[c]["dfa"]) for c in hb])
    rng("lrnNoCrossFetchHost", [100 * nc[c]["closed_fetch_to_opt"] for c in hb])
    rng("lrnFetchAll", [100 * q[c]["closed_fetch_to_opt"] for c in q])
    rng("lrnOverOpt", [q[c]["learned"] / q[c]["opt"] for c in q], "{:.2f}")
    put("lrnBeatsWOne", str(sum(q[c]["learned"] < q[c]["W1"] for c in q)))
    put("lrnBeatsWTwo", str(sum(q[c]["learned"] < q[c]["W2"] for c in q)))
    put("lrnCells", str(len(q)))
    for m, C, tag, _, _ in CELLS:
        r = q[(m, C)]
        put(f"lrnFetch{tag}", f"{100 * r['closed_fetch_to_opt']:.0f}")
        put(f"lrnDep{tag}", f"{100 * r['closed_deployed_to_opt']:.0f}")
        put(f"lrnReads{tag}", f"{r['learned']:.1f}")
        put(f"lrnFetchReads{tag}", f"{r['dfa-fetch']:.1f}")
        put(f"lrnDepReads{tag}", f"{r['dfa']:.1f}")
    with open(P("paper", "wsg_learned.tex"), "w") as f:
        f.write("% generated by scripts/learned_paper.py from prereg/learned_offline.json\n")
        for k in sorted(M):
            f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    with open(P("paper", "tab_learned.tex"), "w") as f:
        f.write("\\begin{table}[t]\\centering\\footnotesize\n")
        f.write("\\caption{A learned admission order, offline: host reads per token on the AIME-25 routing the engine runs, of the "
                "deployed policy (decayed frequency, admissions served by the CPU and then copied: two reads each), the same scores "
                "with each admission read once (single read), the learned order with single-read admission (trained on the model's "
                "mixed-domain trace; 8-bit cross-layer table, as in the engine), Belady within one and four tokens of perfect "
                "foresight, and MIN with bypass. \\emph{closed}: the share of the single-read policy's excess over MIN that the "
                "learned order removes. $^\\dagger$host-bound.}\\label{tab:learned}\n")
        f.write("\\setlength\\tabcolsep{3.5pt}\n\\begin{tabular}{@{}lrrrrrrr@{}}\\toprule\n")
        f.write("cell & deployed & single read & learned & $W{=}1$ & $W{=}4$ & MIN & closed \\\\\\midrule\n")
        for m, C, tag, lab, h in CELLS:
            r = q[(m, C)]
            dag = "$^\\dagger$" if h else ""
            f.write(f"{lab}{dag} & {r['dfa']:.1f} & {r['dfa-fetch']:.1f} & {r['learned']:.1f} & {r['W1']:.1f} & "
                    f"{r['W4']:.1f} & {r['opt']:.1f} & {100 * r['closed_fetch_to_opt']:.0f}\\% \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    print(len(M), "macros")


if __name__ == "__main__":
    main()
