"""Registration timing: for every rental of jobs 093-115 in the ledger, the commit that last changed the job's header
script and its per-host wrapper before the rental, the GitHub push that first published it (prereg/gpu_pushes.json,
the push events of refs/heads/gpu from the GitHub activity API), the rental's creation (gpu/vast_ledger.json, written
just after the rental request returns) and the job's start on the machine (manifest.json start_utc).
Writes paper/wsg_regtime.tex.

    python scripts/reg_timing.py
"""
import datetime as dt
import json
import os
import subprocess

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
G = os.environ.get("MOSL_GPU", "/home/claude/gpu-branch")
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
L = json.load(open(P("gpu", "vast_ledger.json")))
PUSH = sorted(json.load(open(P("prereg", "gpu_pushes.json"))), key=lambda p: p["ts"])


def git(*a):
    return subprocess.run(["git", "-C", G, *a], capture_output=True, text=True).stdout.strip()


def ts(s):
    return dt.datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=dt.timezone.utc).timestamp()


_anc = {}


def is_anc(a, b):
    if (a, b) not in _anc:
        _anc[(a, b)] = subprocess.run(["git", "-C", G, "merge-base", "--is-ancestor", a, b]).returncode == 0
    return _anc[(a, b)]


def push_of(h):
    for p in PUSH:
        if p["type"] in ("push", "force_push", "branch_creation") and git("cat-file", "-t", p["after"]) == "commit" \
                and is_anc(h, p["after"]):
            return ts(p["ts"])
    return None


def main():
    rows = []
    for r in L:
        j = r.get("job") or ""
        if not j[:3].isdigit() or not ("093" <= j[:3] <= "115"):
            continue
        base = j[:3] + "_" + j.split("_", 1)[1] if j[3].isalpha() else j
        st, pushes, commit_gap = r["start"], [], []
        for f in dict.fromkeys([f"jobs/{j}.sh", f"jobs/{base}.sh"]):
            cs = [ln.split() for ln in git("log", "--format=%H %ct", "--", f).splitlines()]
            cs = [(h, int(t)) for h, t in cs if int(t) <= st + 1]
            if cs:
                pushes.append(push_of(cs[0][0])); commit_gap.append(st - cs[0][1])
        mf = f"{G}/results/{j}/manifest.json"
        ms = ts(json.load(open(mf))["start_utc"]) if os.path.exists(mf) else None
        last = max(p for p in pushes if p is not None)
        rows.append(dict(job=j, push_minus_rent=last - st, start_minus_push=(ms - last) if ms else None,
                         commit_before_rent=min(commit_gap)))
    near = [x for x in rows if abs(x["push_minus_rent"]) <= 1.0]
    after = [x for x in rows if x["push_minus_rent"] > 0]
    lag = [x["start_minus_push"] for x in rows if x["start_minus_push"] is not None]
    num = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
    M = dict(rtRentals=str(len(rows)), rtNear=num[len(near)] if len(near) < 10 else str(len(near)),
             rtAfter=num[len(after)] if len(after) < 10 else str(len(after)),
             rtAfterMax=f"{max(x['push_minus_rent'] for x in after):.1f}" if after else "0",
             rtMinLag=f"{min(lag):.0f}", rtCommitMin=f"{min(x['commit_before_rent'] for x in rows):.1f}")
    with open(P("paper", "wsg_regtime.tex"), "w") as f:
        f.write("% generated by scripts/reg_timing.py\n")
        for k in sorted(M):
            f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    print(M)
    for x in near:
        print(x)


if __name__ == "__main__":
    main()
