"""MIN's host reads per token (R*, per layer, with bypass) on the first 20 problems of the gpt-oss routing trace, the
problems the later experiments time, against the full 30-problem trace that the bound uses everywhere
(prereg/speed_limit_v2.json). Writes paper/wsg_rstar.tex.

    python scripts/rstar_twenty.py
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from speed_limit_v2 import per_layer  # noqa: E402

P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
TOK_PER_PROBLEM, N = 256, 20


def main():
    v2 = json.load(open(P("prereg", "speed_limit_v2.json")))
    m = v2["models"]["gpt-oss-120b"]
    z = np.load(m["trace"])
    act = z["act"].astype(np.int64)
    E = int(z["n_expert"])
    assert act.shape[0] == m["T"] == 30 * TOK_PER_PROBLEM
    sub = act[: N * TOK_PER_PROBLEM]
    M, rows = {}, {}
    for C, nm in ((14, "Low"), (32, "Mid")):
        full = m["rows"][str(C)]["reads_per_token"]["exact"]
        twenty = float(per_layer(sub, E, C).sum() / sub.shape[0])
        rows[C] = dict(full=full, first20=twenty)
        M[f"rsTwenty{nm}"] = f"{twenty:.1f}"; M[f"rsAll{nm}"] = f"{full:.1f}"
        M[f"rsDiff{nm}"] = f"{100 * (twenty / full - 1):+.1f}".replace("-", "$-$")
    json.dump(rows, open(P("prereg", "rstar_twenty.json"), "w"), indent=1)
    with open(P("paper", "wsg_rstar.tex"), "w") as f:
        f.write("% generated by scripts/rstar_twenty.py\n")
        for k in sorted(M):
            f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    print(M)


if __name__ == "__main__":
    main()
