"""Machine re-scoring of the hand-encoded scorecard (prereg/scorecard_clauses.json) and of job 099
(prereg/scorecard_099.json, already machine-scored): every clause whose measured value is a number and whose threshold
parses (> x, >= x, < x, <= x, a to b, a-b, [a, b], within +-x, -x to +x) is scored again from its measured value and
interval under the rule in the file's meta.ci_rule, with 'held (point)' split into 'no interval' and 'interval
crosses'. Writes prereg/scorecard_auto.json (agreement with the hand scores, every disagreement) and
paper/wsg_scauto.tex.

    python scripts/scorecard_auto.py
"""
import json
import os
import re
from collections import Counter

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
NUM = r"([+-]?\d+(?:\.\d+)?)"


def predicate(thr):
    t = thr.strip().replace("−", "-").replace("%", "").replace("x", "").strip()
    t = re.sub(r"\s+at every budget$", "", t)
    m = re.fullmatch(r"(>=|<=|>|<)\s*" + NUM, t)
    if m:
        op, v = m.group(1), float(m.group(2))
        return {">": lambda x: x > v, ">=": lambda x: x >= v, "<": lambda x: x < v, "<=": lambda x: x <= v}[op]
    m = re.fullmatch(r"within\s*\+-\s*" + NUM, t)
    if m:
        v = abs(float(m.group(1)))
        return lambda x: -v <= x <= v
    m = re.fullmatch(r"\[\s*" + NUM + r"\s*,\s*" + NUM + r"\s*\]", t) or re.fullmatch(NUM + r"\s*(?:to|-)\s*" + NUM, t)
    if m:
        lo, hi = float(m.group(1)), float(m.group(2))
        if lo > hi:
            lo, hi = hi, lo
        return lambda x: lo <= x <= hi
    return None


def auto(c):
    meas, thr, ci = c.get("measured"), c.get("threshold"), c.get("ci")
    if c.get("status") in ("void", "untested") or not isinstance(meas, (int, float)) or isinstance(meas, bool) or not isinstance(thr, str):
        return None, ""
    ok = predicate(thr)
    if ok is None:
        return None, ""
    if not ok(meas):
        return "failed", ""
    if not (isinstance(ci, list) and len(ci) == 2 and all(isinstance(v, (int, float)) for v in ci)):
        return "held (point)", "no interval"
    if ok(ci[0]) and ok(ci[1]):
        return "held", ""
    return "held (point)", "interval crosses"


def _tex(x):
    import re
    x = str(x).replace("%", "\\%").replace("_", "\\_").replace("&", "\\&")
    x = x.replace(">=", "$\\ge$").replace("<=", "$\\le$")
    x = re.sub(r"(^|\s)>(\s)", r"\1$>$\2", x)
    x = re.sub(r"(^|\s)<(\s)", r"\1$<$\2", x)
    return re.sub(r"(\d) us\b", r"\1 $\\mu$s", x)


def write_099(j99, path, job="099", title="the host panel", script="panel\\_099.py", label="scorecard099"):
    """a machine-scored job's clauses (job 099: scripts/panel_099.py; job 100: scripts/job100.py) as a longtable for the supplement"""
    st = Counter(c["status"] for c in j99)
    with open(path, "w") as f:
        f.write(f"% Generated by scripts/scorecard_auto.py from prereg/scorecard_{job}.json; do not edit by hand.\n")
        f.write("\\begin{footnotesize}\n\\begin{longtable}{@{}p{0.13\\textwidth}p{0.42\\textwidth}p{0.20\\textwidth}p{0.10\\textwidth}p{0.10\\textwidth}@{}}\n")
        hosts = {"099": "Hosts Pa--Pj; cells gpt-oss 11\\% (g11) and 25\\% (g25), Qwen3 12.5\\% (P10).",
                 "100": "Hosts a (Pd again), b (5700X3D), c (Ph again), f (9950X, x8 link), e (13900KF, never ran); cells gpt-oss 11\\% (g11) and 25\\% (g25).",
                 "101": "Hosts a (Pf again), b (9800X3D, slower link); cells gpt-oss 11\\% (g11) and 25\\% (g25)."}[job]
        f.write(f"\\caption{{Job {job} ({title}), scored by machine by \\texttt{{scripts/{script}}} under the same rule. "
                f"Totals: {len(j99)} clauses, {st.get('held', 0)} held, {st.get('held (point)', 0)} held (point), "
                f"{st.get('failed', 0)} failed, {st.get('untested', 0)} untested. {hosts} Measured: the point estimate and, where one "
                "exists, the 95\\% interval (bootstrap over problems within the host; pooled clauses have none).}"
                f"\\label{{tab:{label}}}\\\\\n")
        hdr = "\\toprule\nClause & Statement & Measured & Predicted & Status \\\\\\midrule\n"
        f.write(hdr + "\\endfirsthead\n" + hdr + "\\endhead\n\\midrule\\multicolumn{5}{r}{\\emph{continued}}\\\\\n\\endfoot\n\\bottomrule\n\\endlastfoot\n")
        for c in j99:
            m = c["measured"]
            ms = "--" if m is None else (f"{m:.3f}" if abs(m) < 10 else f"{m:.1f}")
            if c.get("ci"):
                ms += f" [{c['ci'][0]:.3f}, {c['ci'][1]:.3f}]"
            stt = c["status"] if c["status"] != "failed" else "\\textbf{failed}"
            f.write(f"{_tex(c['id'][3:].lstrip('-'))} & {_tex(c['short'])} & {ms} & {_tex(c['threshold'])} & {stt} \\\\\n")
        f.write("\\end{longtable}\n\\end{footnotesize}\n")


def main():
    d = json.load(open(P("prereg", "scorecard_clauses.json")))
    rows, dis = [], []
    for j in d["jobs"]:
        for c in j["clauses"]:
            a, why = auto(c)
            rows.append(dict(id=c["id"], hand=c["status"], auto=a, why=why))
            if a is not None and a != c["status"]:
                dis.append(dict(id=c["id"], threshold=c.get("threshold"), measured=c.get("measured"), ci=c.get("ci"), hand=c["status"], auto=a, note=c.get("note", "")))
    n_auto = sum(r["auto"] is not None for r in rows)
    agree = sum(r["auto"] == r["hand"] for r in rows if r["auto"] is not None)
    why = Counter(r["why"] for r in rows if r["auto"] == "held (point)")
    p99 = P("prereg", "scorecard_099.json")
    j99 = json.load(open(p99))["clauses"] if os.path.exists(p99) else []
    out = dict(n=len(rows), n_auto=n_auto, agree=agree, disagreements=dis, point_reasons=dict(why),
               job099=dict(n=len(j99), status=dict(Counter(c["status"] for c in j99)), why=dict(Counter(c["why"] for c in j99 if c["why"]))))
    json.dump(out, open(P("prereg", "scorecard_auto.json"), "w"), indent=1)
    det = sum(1 for x in dis if x["hand"] == "held" and x["auto"] == "held (point)" and x["ci"] is None)
    out["deterministic_held_outright"] = det
    json.dump(out, open(P("prereg", "scorecard_auto.json"), "w"), indent=1)
    M = dict(scaN=str(len(rows)), scaAuto=str(n_auto), scaAgree=str(agree), scaDisagree=str(len(dis)), scaDet=str(det),
             scaOther=str(len(dis) - det),
             scaNoInterval=str(why.get("no interval", 0)), scaCrosses=str(why.get("interval crosses", 0)))
    st = Counter(c["status"] for c in j99)
    M.update(scbN=str(len(j99)), scbHeld=str(st.get("held", 0)), scbPoint=str(st.get("held (point)", 0)), scbFailed=str(st.get("failed", 0)),
             scbUntested=str(st.get("untested", 0)))
    with open(P("paper", "wsg_scauto.tex"), "w") as f:
        f.write("% generated by scripts/scorecard_auto.py\n")
        for k in sorted(M):
            f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    if j99:
        write_099(j99, P("paper", "tab_scorecard_099.tex"))
    p101 = P("prereg", "scorecard_101.json")
    if os.path.exists(p101):
        write_099(json.load(open(p101))["clauses"], P("paper", "tab_scorecard_101.tex"), job="101",
                  title="the crossover machine relaunched, and a second 9800X3D", script="job101.py", label="scorecard101")
    p100 = P("prereg", "scorecard_100.json")
    if os.path.exists(p100):
        j100 = json.load(open(p100))["clauses"]
        write_099(j100, P("paper", "tab_scorecard_100.tex"), job="100", title="foresight on the deployed path; the model from the probe alone",
                  script="job100.py", label="scorecard100")
        st = Counter(c["status"] for c in j100)
        M.update(sccN=str(len(j100)), sccHeld=str(st.get("held", 0)), sccPoint=str(st.get("held (point)", 0)), sccFailed=str(st.get("failed", 0)),
                 sccUntested=str(st.get("untested", 0)))
        with open(P("paper", "wsg_scauto.tex"), "a") as f:
            for k in ("sccN", "sccHeld", "sccPoint", "sccFailed", "sccUntested"):
                f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    print(M)
    for x in dis[:40]:
        print(x)


if __name__ == "__main__":
    main()
