"""The registered tests of eq. (sum), one row per job (105-108), from the scored outputs prereg/job10[5-8].json and the
raw results' GPU UUIDs: the form and band registered, the machines (and how many no earlier launch had rented), the
cells within the band, the same for the new machines alone, the median |error| and the verdict as registered; plus the
verdict without the hosts set aside after the fact. Writes paper/tab_regtests.tex.

    python scripts/tab_regtests.py
"""
import glob
import json
import os

import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
RES = os.environ.get("MOSL_RESULTS", "/home/claude/gpu-branch/results")
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731


def uuid(dirname):
    f = f"{RES}/{dirname}/nvidia-smi-q.txt"
    if os.path.exists(f):
        for ln in open(f):
            if "GPU UUID" in ln:
                return ln.split(":", 1)[1].strip()
    return None


def earlier_uuids(job):
    out = set()
    for d in glob.glob(f"{RES}/*"):
        b = os.path.basename(d)
        if b[:3].isdigit() and int(b[:3]) < job:
            u = uuid(b)
            if u:
                out.add(u)
    return out


def rows():
    R = []
    # job 105: the plain form, gpt-oss 11% and 25%, band 6%, pooled median 4%
    hs = json.load(open(P("prereg", "job105.json")))["hosts"]
    prev = earlier_uuids(105)
    cells = [(h["dir"], c["sum_law"]["err"]) for h in hs for c in h["cells"].values() if "sum_law" in c]
    new = {h["dir"] for h in hs if uuid(h["dir"]) not in prev}
    R.append(dict(job="105", form="plain", band=0.06, models="gpt-oss", hosts=len(hs), new=len(new), cells=cells, newset=new,
                  excl=None))
    # job 106: the overlap form, both models; two hosts were set aside after the fact (wrong outputs; rounds far apart)
    hs = json.load(open(P("prereg", "job106.json")))["hosts"]
    prev = earlier_uuids(106)
    cells = [(h["dir"], c["err"]["base"]["olap"]) for h in hs for c in h["cells"].values() if "err" in c and "base" in c["err"]]
    new = {h["dir"] for h in hs if uuid(h["dir"]) not in prev}
    keep = [x for x in cells if x[0][:4] not in ("106c", "106d")]
    R.append(dict(job="106", form="overlap", band=0.06, models="both", hosts=len(hs), new=len(new), cells=cells, newset=new,
                  excl=keep))
    # jobs 107 and 108: the overlap form; only machines that passed the registered checks count
    for job, band, models in (("107", 0.06, "both"), ("108", 0.08, "gpt-oss")):
        hs = [h for h in json.load(open(P("prereg", f"job{job}.json")))["hosts"] if h["valid"]]
        cells = [(h["dir"], c["err"]["base"]["olap"]) for h in hs for c in h["cells"].values() if "err" in c and "base" in c["err"]]
        keep = [x for x in cells if not any(h["dir"] == x[0] and h.get("G_fallback") for h in hs)] if job == "108" else None
        R.append(dict(job=job, form="overlap", band=band, models=models, hosts=len(hs), new=len(hs), cells=cells,
                      newset={h["dir"] for h in hs}, excl=keep))
    return R


def verdict(cells, band, job):
    a = np.abs([e for _, e in cells])
    if job == "108":   # 8% at every cell, at most one cell beyond 6%, median at most 4%
        ok = (a <= band).all() and (a > 0.06).sum() <= 1 and np.median(a) <= 0.04
    else:              # 6% at every cell, median at most 4%
        ok = (a <= band).all() and np.median(a) <= 0.04
    return "held" if ok else "failed"


def main():
    R = rows()
    with open(P("paper", "tab_regtests.tex"), "w") as f:
        f.write("% generated by scripts/tab_regtests.py from prereg/job105.json .. job108.json and the results' GPU UUIDs\n")
        f.write("\\begin{table*}[t]\\centering\\footnotesize\n\\caption{The four registered tests of \\cref{eq:sum}. A \\emph{cell} is "
                "one model at one budget on one machine. \\emph{New}: machines no earlier launch had rented. Each test registered "
                "a band for every cell and a median error of at most 4\\%; job 108 also allowed at most one cell beyond 6\\%. Jobs "
                "107 and 108 count only the machines that passed their registered validity checks. The last column sets aside, "
                "after the fact, the hosts the text discusses: in job 106 the two that computed wrong outputs or ran unsteadily, "
                "in job 108 the one whose GPU compute could not be profiled.}\\label{tab:regtests}\n")
        f.write("\\begin{tabular}{@{}llllrrrrll@{}}\\toprule\n")
        f.write("Job & Form & Models & Band & Machines (new) & Cells within & New machines' cells & Median & As registered & "
                "Without them \\\\\\midrule\n")
        for r in R:
            a = np.abs([e for _, e in r["cells"]])
            nc = [e for d, e in r["cells"] if d in r["newset"]]
            ex = "--"
            if r["excl"] is not None:
                ea = np.abs([e for _, e in r["excl"]])
                ex = f"{verdict(r['excl'], r['band'], r['job'])} ({int((ea <= r['band']).sum())}/{len(ea)}, {100 * np.median(ea):.1f}\\%)"
            f.write(f"{r['job']} & {r['form']} & {r['models']} & {100 * r['band']:.0f}\\% & {r['hosts']} ({r['new']}) & "
                    f"{int((a <= r['band']).sum())}/{len(a)} & {sum(abs(e) <= r['band'] for e in nc)}/{len(nc)} & "
                    f"{100 * np.median(a):.1f}\\% & {verdict(r['cells'], r['band'], r['job'])} & {ex} \\\\\n")
        f.write("\\bottomrule\\end{tabular}\n\\end{table*}\n")
    for r in R:
        print(r["job"], r["hosts"], r["new"], len(r["cells"]))


if __name__ == "__main__":
    main()
