"""The prediction log as a table: every registered job from 073 on, what it tested, and how its clauses scored
(held with an interval, held on the point estimate, failed, untested or void), from prereg/scorecard_clauses.json
(jobs 073-098, hand-scored) and prereg/scorecard_099.json .. scorecard_111.json (machine-scored). Writes
paper/tab_prereg.tex.

    python scripts/tab_prereg.py
"""
import json
import os
from collections import Counter, OrderedDict

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731

WHAT = {
    "073": "ours against FreeToken, same host", "074": "the 40\\% budget fixed", "074b": "server overhead",
    "075": "RTX PRO 6000 at 40--60\\%", "076": "the system table on an RTX 5090", "077": "competitors, gpt-oss",
    "078": "Qwen3, four systems", "079": "Qwen3 profile", "080": "the fetch split", "081": "the system table with the calibrated fetch split",
    "082": "held-out prompts and steady state (review run 1)", "083": "gpt-oss, long outputs on hard held-out problems", "084": "all-in-VRAM column and traces (voided: throttled card)",
    "084b": "all-in-VRAM column and traces, rerun", "084c": "gpt-oss trace", "085": "a slower PCIe link, gpt-oss",
    "085b": "a slower PCIe link, Qwen3", "086": "Qwen3.6", "087": "ablation with a static cache",
    "088": "slow link, fair comparison", "089": "the system table on a second host", "090": "output parity against all-in-VRAM (RTX PRO 6000)",
    "091": "the grid on an RTX 4090", "092": "the grid on an RTX 3090", "093": "first foresight oracles",
    "094": "oracles that minimise bytes", "095": "single-read oracles", "096": "the oracle factorial",
    "097": "the learned admission order", "098": "FreeToken tuned", "099": "the host panel", "100": "windows of foresight",
    "101": "the crossover by link ratio", "102": "the read-schedule microbenchmark",
    "103": "fewest-admission schedule (plan not run)", "104": "fewest-admission schedule",
    "105": "\\cref{eq:sum}, plain form; layer-ahead copy; fewest-admission set", "106": "\\cref{eq:sum} with overlap; admitting less; slow links by round",
    "107": "\\cref{eq:sum} on new machines; admitting less; fewest-admission loads", "108": "\\cref{eq:sum} on new desktop-class machines",
    "109": "the 2$\\times$2 and policies without foresight on new machines", "110": "the RTX 5090 trend on RTX 4090s (stopped by V1)",
    "111": "job 110 relaunched, V1 corrected",
    "112": "higher-ratio RTX 4090s; timing control; second probe",
    "113": "the two-read path with the in-step fetches off",
    "114": "the 2$\\times$2 with the in-step fetches off",
}


def main():
    jobs = OrderedDict()
    for j in json.load(open(P("prereg", "scorecard_clauses.json")))["jobs"]:
        key = j["job"][:3] if j["job"][:3] in ("096", "097") else j["job"]
        jobs.setdefault(key, Counter()).update(c["status"] for c in j["clauses"])
    jobs = OrderedDict(sorted(jobs.items()))
    cond = {}   # validity conditions ("at least k valid hosts"): operational, not predictions, so counted apart
    for k in ("099", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114"):
        if not os.path.exists(P("prereg", f"scorecard_{k}.json")):
            continue
        cl = json.load(open(P("prereg", f"scorecard_{k}.json")))["clauses"]
        jobs.setdefault(k, Counter()).update(c["status"] for c in cl if not c["id"].endswith("-valid"))
        cv = [c for c in cl if c["id"].endswith("-valid")]
        if cv:
            cond[k] = (sum(c["status"].startswith("held") for c in cv), sum(c["status"] == "failed" for c in cv))
    with open(P("paper", "tab_prereg.tex"), "w") as f:
        f.write("% generated by scripts/tab_prereg.py\n\\begin{table}[p]\\centering\\scriptsize\n")
        f.write("\\caption{Every registered job from 073 on and how its clauses scored: \\emph{held} with a 95\\% interval on the "
                "predicted side (or outright, for deterministic counts), held on the point estimate only, failed, and untested or void. Jobs 073--098 were scored by "
                "hand, the rest by script; the scorecard lists every clause. \\emph{Cond.}: a job's validity condition (at least $k$ valid "
                "machines), met or not; it is operational, not a prediction, and is not counted in the other columns.}\\label{tab:prereg}\n")
        f.write("\\setlength\\tabcolsep{3pt}\\begin{tabular}{@{}llrrrrc@{}}\\toprule\nJob & What it tested & Held & Point & Failed & Untested & Cond. \\\\\\midrule\n")
        tot = Counter()
        cm = cu = 0
        for k, c in jobs.items():
            if not sum(c.values()):
                continue
            tot.update(c)
            m, u = cond.get(k, (0, 0)); cm += m; cu += u
            cc = "--" if k not in cond else ("met" if u == 0 else "not met")
            f.write(f"{k} & {WHAT.get(k, '')} & {c.get('held', 0)} & {c.get('held (point)', 0)} & {c.get('failed', 0)} & "
                    f"{c.get('untested', 0) + c.get('void', 0)} & {cc} \\\\\n")
        f.write(f"\\midrule all & & {tot.get('held', 0)} & {tot.get('held (point)', 0)} & {tot.get('failed', 0)} & "
                f"{tot.get('untested', 0) + tot.get('void', 0)} & {cm} met, {cu} not \\\\\n")
        f.write("\\bottomrule\\end{tabular}\\end{table}\n")
    print(sum(tot.values()), dict(tot))


if __name__ == "__main__":
    main()
