"""The value of partial foresight for the paper: macros (paper/wsg_valuemap.tex) from the replay map on the AIME routing
(prereg/value_map.json: always-admit fallback; prereg/value_map_k1.json: the deployed margin), and Figure figs/value.pdf
with the panel's engine measurements (prereg/panel_099.json) on top when they exist.

Share = (reads of admit-every-miss - reads of the window) / (reads of admit-every-miss - reads of MIN with one read).

    python scripts/value_paper.py
"""
import json
import os

import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
CELLS = [("gpt-oss-120b C14", "gpt-oss 11%", "Low"), ("gpt-oss-120b C32", "gpt-oss 25%", "Mid"),
         ("qwen3-30b-a3b C16", "Qwen3 12.5%", "Qlow"), ("qwen3-30b-a3b C32", "Qwen3 25%", "Qmid")]
WS = [1, 2, 4, 8, 16, 32]


def w_at(share, target=0.5):
    """smallest W (log-interpolated) at which the exact share reaches target"""
    xs = [0.0] + [np.log(w) for w in WS]
    ys = [0.0] + [share[str(w)] for w in WS]
    for i in range(1, len(xs)):
        if ys[i] >= target:
            if i == 1:
                return float(np.exp(xs[1])) * target / max(ys[1], 1e-9)
            f = (target - ys[i - 1]) / (ys[i] - ys[i - 1])
            return float(np.exp(xs[i - 1] + f * (xs[i] - xs[i - 1])))
    return float("inf")


def main():
    vm = json.load(open(P("prereg", "value_map.json")))
    M = {}
    halves = []
    for key, lab, nm in CELLS:
        c = vm[key]
        sh = c["share"]
        wh = w_at(sh)
        halves.append(wh)
        M[f"vmHalf{nm}"] = f"{wh:.0f}" if wh >= 2 else f"{wh:.1f}"
        for w, wn in ((1, "One"), (2, "Two"), (4, "Four"), (8, "Eight"), (16, "Sixteen")):
            M[f"vmShare{wn}{nm}"] = f"{sh[str(w)]:.2f}"
        f = c["share_fill"]
        d = c["share_drop"]
        M[f"vmEightHalf{nm}"] = f"{f['W8_r0.5']:.2f}"
        M[f"vmAllHalf{nm}"] = f"{f['W0_r0.5']:.2f}"
        M[f"vmEightHalfDrop{nm}"] = f"{d['W8_r0.5']:.2f}"
        M[f"vmAllHalfDrop{nm}"] = f"{d['W0_r0.5']:.2f}"
        M[f"vmAa{nm}"] = f"{c['online_hybrid']:.1f}"
        M[f"vmMin{nm}"] = f"{c['min_fetch']:.1f}"
    M["vmHalfMin"] = f"{min(halves):.0f}"
    M["vmHalfMax"] = f"{max(halves):.0f}"
    # fill vs drop: the largest difference in share at equal r over all cells and windows
    diffs = [abs(vm[k]["share_fill"][x] - vm[k]["share_drop"][x]) for k, _, _ in CELLS for x in vm[k]["share_fill"]]
    M["vmFillDropMax"] = f"{max(diffs):.2f}"
    # layer-ahead prediction (layer l+1's router on the residual after layer l's attention) on gpt-oss-120b, from the
    # lookahead records of job 063 (fields act[k] and mid1[8] per layer): recall at k and with 8 candidates
    la = "/home/claude/gpu-branch/results/063_lookahead@vast/la_gpt-oss-120b.bin"
    if os.path.exists(la):
        meta = json.load(open(la + ".json"))
        L, k = int(meta["n_layer"]), int(meta["k"])
        raw = np.fromfile(la, np.int16)
        stride = 2 + L * (2 * k + 24)
        rec = raw[: len(raw) // stride * stride].reshape(-1, stride)
        blk = lambda l: rec[:, 2 + l * (2 * k + 24): 2 + (l + 1) * (2 * k + 24)]  # noqa: E731
        rk, r8 = [], []
        for l in range(L - 1):
            nxt, mid = blk(l + 1)[:, :k], blk(l)[:, 2 * k: 2 * k + 8]
            rk.append((nxt[:, :, None] == mid[:, None, :k]).any(-1).mean())
            r8.append((nxt[:, :, None] == mid[:, None, :]).any(-1).mean())
        M["laRecallK"] = f"{100 * np.mean(rk):.0f}"
        M["laRecallEight"] = f"{100 * np.mean(r8):.0f}"
    with open(P("paper", "wsg_valuemap.tex"), "w") as f:
        f.write("% generated by scripts/value_paper.py from prereg/value_map.json\n")
        for k in sorted(M):
            f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    print(M)
    table(vm)
    figure(vm)


def table(vm):
    """paper/tab_value.tex: per cell, reads of admit-every-miss and MIN, and the share of the gap each window closes"""
    k1 = json.load(open(P("prereg", "value_map_k1.json"))) if os.path.exists(P("prereg", "value_map_k1.json")) else {}
    fl = json.load(open(P("prereg", "forecaster_linear.json"))) if os.path.exists(P("prereg", "forecaster_linear.json")) else {}
    rows = []
    for key, lab, nm in CELLS:
        if key not in vm:
            continue
        c = vm[key]
        sh, f, d = c["share"], c["share_fill"], c["share_drop"]
        cells = [f"{c['online_hybrid']:.1f}", f"{c['min_fetch']:.1f}"] + [f"{sh[str(w)]:.2f}" for w in (1, 2, 4, 8, 16)]
        cells += [f"{f['W8_r0.5']:.2f} / {d['W8_r0.5']:.2f}", f"{f['W0_r0.5']:.2f} / {d['W0_r0.5']:.2f}"]
        mk, C = key.split(" C")
        ridge = ""
        if mk in fl and C in fl[mk]["cells"]:
            ridge = f"{fl[mk]['cells'][C]['ridge_W4_share']:.2f}"
        cells.append(ridge or "--")
        if key in k1:
            cells.append(f"{k1[key]['share']['4']:.2f}")
        else:
            cells.append("--")
        rows.append(lab.replace("%", r"\%") + " & " + " & ".join(cells) + r" \\")
    with open(P("paper", "tab_value.tex"), "w") as fo:
        fo.write("% generated by scripts/value_paper.py\n")
        fo.write(r"""\begin{table*}[t]\centering\small
\caption{Partial foresight on the AIME routing the engine runs: host reads per token of admitting every miss and of MIN
with one read, and the share of the gap between them that each window closes (\cref{tab:configs}). Recall 0.5:
each future expert kept with probability 0.5 and replaced by a random one (fill) or left out (drop); means of three
seeds. Linear: the ridge forecaster of \cref{app:value} with a 4-token window. $\kappa{=}1$: the same exact 4-token
window with the deployed margin instead of admitting every miss beyond it, as a share of its own gap.}\label{tab:value}
\begin{tabular}{lrrrrrrrrrrr}\toprule
 & \multicolumn{2}{c}{Reads per token} & \multicolumn{5}{c}{Exact window $W$ (tokens)} & \multicolumn{2}{c}{Recall 0.5, fill / drop} & Linear & $\kappa{=}1$ \\
Budget & every miss & MIN & 1 & 2 & 4 & 8 & 16 & $W{=}8$ & all & $W{=}4$ & $W{=}4$ \\\midrule
""")
        fo.write("\n".join(rows) + "\n\\bottomrule\\end{tabular}\\end{table*}\n")


def figure(vm):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    pn = None
    if os.path.exists(P("prereg", "panel_099.json")):
        pn = json.load(open(P("prereg", "panel_099.json")))
    show = [c for c in CELLS if c[0] in vm]
    fig, axs = plt.subplots(1, len(show), figsize=(7.0, 2.1), sharey=True)
    xs = [1, 2, 4, 8, 16, 32, 64]
    for ax, (key, lab, nm) in zip(axs, show):
        c = vm[key]
        ex = [c["share"][str(w)] for w in WS] + [c["share"]["0"]]
        ax.plot(xs, ex, "-", color="#1f4e79", lw=1.6, label="exact")
        nz = [c["share_fill"].get(f"W{w}_r0.5") for w in (4, 8, 16)] + [c["share_fill"]["W0_r0.5"]]
        ax.plot([4, 8, 16, 64], nz, "--", color="#c55a11", lw=1.4, label="recall 0.5")
        fl = json.load(open(P("prereg", "forecaster_linear.json"))) if os.path.exists(P("prereg", "forecaster_linear.json")) else {}
        mk_, C_ = key.split(" C")
        if mk_ in fl and C_ in fl[mk_]["cells"]:
            fc = fl[mk_]["cells"][C_]
            ax.plot([1, 2, 4, 8], [fc[f"ridge_W{w}_share"] for w in (1, 2, 4, 8)], ":", color="#4a3aa7", lw=1.5, marker=".", ms=4,
                    label="linear forecaster")
        if pn:
            spec = {"w1": (1, "o", "#1f4e79"), "w2": (2, "o", "#1f4e79"), "w4": (4, "o", "#1f4e79"), "w16": (16, "o", "#1f4e79"),
                    "w8r5": (8, "s", "#c55a11"), "allr5": (64, "s", "#c55a11")}
            for x, (w, mk, col) in spec.items():
                vals = [h["cells"][lab]["time_share"][x] for h in pn["hosts"] if lab in h["cells"] and x in h["cells"][lab].get("time_share", {})]
                if vals:
                    m = float(np.mean(vals))
                    ax.errorbar([w], [m], yerr=[[m - min(vals)], [max(vals) - m]], fmt=mk, color=col, ms=4.5, capsize=2,
                                mfc="white", mew=1.2)
        ax.set_xscale("log", base=2)
        ax.set_xticks(xs)
        ax.set_xticklabels(["1", "2", "4", "8", "16", "32", "all"], fontsize=7)
        ax.set_title(lab, fontsize=8)
        ax.axhline(0.5, color="0.7", lw=0.6, ls=":")
        ax.set_ylim(-0.05, 1.05)
        ax.tick_params(labelsize=7)
        ax.set_xlabel("tokens of foresight $W$", fontsize=7)
    axs[0].set_ylabel("share of MIN's gain", fontsize=8)
    axs[0].legend(fontsize=6.5, frameon=False, loc="upper left")
    fig.tight_layout(pad=0.3)
    fig.savefig(P("paper", "figs", "value.pdf"))
    fig.savefig(P("paper", "figs", "value.png"), dpi=160)


if __name__ == "__main__":
    main()
