"""Uncertainty on the horizon rule's held-out comparison, and its residual trend with budget, from
prereg/foresight/w50_distinct.json (scripts/w50_rebaseline.py). The leave-one-model-out errors of the three rules are
recomputed exactly as there; a bootstrap over models (2,000 resamples, a resampled model contributing all its budget
points) gives an interval for the difference in median log error between the distinct-expert rule and the power law.
Writes paper/wsg_w50boot.tex.

    python scripts/w50_lomo_boot.py
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)
from scripts.w50_rebaseline import WS  # noqa: E402

P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731


def main():
    d = json.load(open(P("prereg", "foresight", "w50_distinct.json")))
    res = d["models"]
    rows = [(m, p) for m, v in res.items() for p in v["pts"]]

    def inv(v, target):
        if target <= v["k"]:
            return target / v["k"]
        return float(np.exp(np.interp(np.log(target), np.log(v["D"]), np.log(WS))))
    err = {}   # model -> rule -> list of |log error|
    for hold in res:
        tr = [p for m, p in rows if m != hold]
        te = [p for m, p in rows if m == hold]
        if not te:
            continue
        b, a = np.polyfit(np.log([p["Ck"] for p in tr]), np.log([p["W50"] for p in tr]), 1)
        c = np.median([p["D_over_C"] for p in tr])
        e = err.setdefault(hold, {"power": [], "distinct": []})
        for p in te:
            e["power"].append(abs(np.log(np.exp(a) * p["Ck"] ** b / p["W50"])))
            e["distinct"].append(abs(np.log(inv(res[hold], c * p["C"]) / p["W50"])))
    models = sorted(err)
    rng = np.random.default_rng(50)
    diffs, wins = [], 0
    for _ in range(2000):
        pick = [models[i] for i in rng.integers(0, len(models), len(models))]
        dp = np.median([x for m in pick for x in err[m]["power"]])
        dd = np.median([x for m in pick for x in err[m]["distinct"]])
        diffs.append(np.exp(dp) / np.exp(dd))
        wins += dd < dp
    M = {}
    M["dbRatioLo"] = f"{np.percentile(diffs, 2.5):.2f}"
    M["dbRatioHi"] = f"{np.percentile(diffs, 97.5):.2f}"
    M["dbWinPct"] = f"{100 * wins / 2000:.0f}"
    # the residual trend: D(W50)/C falls with the budget within a model
    dec = 0
    n3 = 0
    for m, v in res.items():
        pts = sorted(v["pts"], key=lambda p: p["C"])
        if len(pts) >= 2 and pts[-1]["D_over_C"] < pts[0]["D_over_C"]:
            dec += 1
        n3 += 1
    M["dbTrendDown"] = str(dec)
    M["dbTrendModels"] = str(n3)
    with open(P("paper", "wsg_w50boot.tex"), "w") as f:
        f.write("% generated by scripts/w50_lomo_boot.py\n")
        for k in sorted(M):
            f.write(f"\\newcommand{{\\{k}}}{{{M[k]}}}\n")
    print(M)


if __name__ == "__main__":
    main()
